version: "3"
services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=
            - MONGO_INITDB_ROOT_PASSWORD=
        volumes:
            - ./db:/data/db

    lynx:
        image: jackbailey/lynx
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=
            - DB_PASSWORD=
            - JWT_KEY=
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=false
            - HOME_REDIRECT=/dash/overview

            ## DO NOT CHANGE THESE:
            - DB_HOST=db
            - DB_PORT=27017
