name: Build Docker Image - Indev

on:
    push:
        branches-ignore: ["main"]
        paths-ignore: ["**.md"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set docker tag dynamically
              run: |
                BRANCH="${GITHUB_REF##*/}"
                echo "TAG=${BRANCH}-beta" >> $GITHUB_ENV
            - name: docker login
              env:
                  DOCKER_USER: jackbailey
                  DOCKER_PASS: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag jackbailey/lynx:$TAG --tag jackbailey/lynx:beta
            - name: Docker Push
              run: docker push jackbailey/lynx:$TAG --all-tags
