name: Build Docker Image - Production

on:
    push:
        branches: ["main"]
        paths-ignore: ["**.md"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Get version
              run: |
                IFS='.' read -ra VERSION <<< "$(cat VERSION)"

                MAJOR="${VERSION[0]}"
                MINOR="${VERSION[0]}.${VERSION[1]}"
                PATCH="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"

                IMAGE=jackbailey/lynx
                DOCKER_TAGS="-t $IMAGE:$MAJOR -t $IMAGE:$MINOR -t $IMAGE:$PATCH -t $IMAGE:latest"

                echo "DOCKER_TAGS=$DOCKER_TAGS" >> $GITHUB_ENV
            - name: docker login
              env:
                  DOCKER_USER: jackbailey
                  DOCKER_PASS: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: Build the Docker image
              run: docker build . --file Dockerfile $DOCKER_TAGS
            - name: Docker Push
              run: docker push jackbailey/lynx --all-tags